name: Publiser workflows til andre repoer

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Test scenario tags'
        required: true
        type: boolean
        default: false

env:
  DRY_RUN: ${{ inputs.dry_run }}


jobs:
  build-and-publish-on-main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read list of default apps
        run: |
          echo "DEFAULT_APPS=$(cat ./config/default_include_apps.conf | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Distribute workflows
        run: |
          ./distribute_workflows.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          TEAM_NAME: ""
          INCLUDE: ${{ env.DEFAULT_APPS }}
          EXCLUDE: ""
          DELETE_CONFIG: "./config/workflow_files_to_delete.conf"
