name: Publiser workflows til andre repoer

on:
  repository_dispatch:
    types: distribute-workflows

env:
  DRY_RUN: ${{ github.event.client_payload.dry_run }}

jobs:
  build-and-publish-on-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read list of default apps
        run: |
          echo "DEFAULT_APPS=$(cat default_include_apps.conf | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Distribute workflows
        run: |
          ./distribute_workflows.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          TEAM_NAME: ""
          INCLUDE: ${{ env.DEFAULT_APPS }}
          EXCLUDE: ""
